/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pages;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import constants.models.ListModels;
import functions.PageP;
import functions.Setting;
import langs.LangM;

/**
 *
 * @author bismih
 */
public class SettingP extends javax.swing.JFrame {

    /**
     * Creates new form Setting
     */
    public SettingP() {
        initComponents();
        cmb_lang.setModel(ListModels.cmbLangList());
        cmb_theme.setModel(ListModels.cmbThemeList());
        LangProces();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_setting = new javax.swing.JPanel();
        cmb_lang = new javax.swing.JComboBox<>();
        lb_lang = new javax.swing.JLabel();
        btn_choseColor = new javax.swing.JButton();
        textFeild1 = new view.TextField.TextFeild();
        buttonN1 = new view.buttons.ButtonN();
        bt_seeLog = new view.buttons.ButtonN();
        bt_saveLog = new view.buttons.ButtonN();
        jScrollPane4 = new javax.swing.JScrollPane();
        txa_log = new javax.swing.JTextArea();
        cmb_theme = new javax.swing.JComboBox<>();
        lb_theme = new javax.swing.JLabel();
        bt_saveTheme = new view.buttons.ButtonN();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        saveLog = new javax.swing.JMenuItem();
        close = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_setting.setMinimumSize(new java.awt.Dimension(700, 600));
        pnl_setting.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmb_lang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnl_setting.add(cmb_lang, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 52, 174, 45));

        lb_lang.setText("Dil");
        pnl_setting.add(lb_lang, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 27, -1, -1));

        btn_choseColor.setText("Kenar rengini seç");
        btn_choseColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_choseColorActionPerformed(evt);
            }
        });
        pnl_setting.add(btn_choseColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, -1, -1));

        textFeild1.setEnabled(false);
        pnl_setting.add(textFeild1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 90, 30));

        buttonN1.setText("button");
        pnl_setting.add(buttonN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, 77, -1));

        bt_seeLog.setText("log kyadını çıkar");
        bt_seeLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_seeLogActionPerformed(evt);
            }
        });
        pnl_setting.add(bt_seeLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 216, 142, 41));

        bt_saveLog.setText("log kaydını bilgsiyara kaydet");
        bt_saveLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_saveLogActionPerformed(evt);
            }
        });
        pnl_setting.add(bt_saveLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 263, 207, 41));

        txa_log.setColumns(20);
        txa_log.setRows(5);
        jScrollPane4.setViewportView(txa_log);

        pnl_setting.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 322, 717, 338));

        cmb_theme.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnl_setting.add(cmb_theme, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 52, 174, 45));

        lb_theme.setText("Tema");
        pnl_setting.add(lb_theme, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 27, -1, -1));

        bt_saveTheme.setText("Kaydet");
        bt_saveTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_saveThemeActionPerformed(evt);
            }
        });
        pnl_setting.add(bt_saveTheme, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 130, 40));

        jMenu1.setText("File");

        saveLog.setText("jMenuItem1");
        saveLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveLogActionPerformed(evt);
            }
        });
        jMenu1.add(saveLog);

        close.setText("jMenuItem2");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jMenu1.add(close);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_setting, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_setting, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_choseColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_choseColorActionPerformed
        PageP.openPage(new ColorChoser(), LangM.colorChoser);
    }//GEN-LAST:event_btn_choseColorActionPerformed

    private void bt_saveThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_saveThemeActionPerformed
        String lang = cmb_lang.getSelectedIndex() == 0 ? "tr" : "en";
        String theme = cmb_theme.getSelectedIndex() == 0 ? "darkOrange" : "darkBlue";
        try {
            Setting.saveSetting(theme, lang);
            JOptionPane.showMessageDialog(rootPane, LangM.saving);
        } catch (Exception e) {
            e.printStackTrace();
            Setting.addLog("\n"+e.getMessage()+getClass().getName());
        }
    }//GEN-LAST:event_bt_saveThemeActionPerformed

    private void bt_seeLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_seeLogActionPerformed
        txa_log.setText(Setting.log);
    }//GEN-LAST:event_bt_seeLogActionPerformed

    private void bt_saveLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_saveLogActionPerformed
        saveLog();
    }//GEN-LAST:event_bt_saveLogActionPerformed

    private void saveLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveLogActionPerformed
        saveLog();
    }//GEN-LAST:event_saveLogActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeActionPerformed

public void saveLog() {
    JFileChooser fc=new JFileChooser();
    fc.showOpenDialog(this);
    File file=fc.getSelectedFile();
    try {
        FileWriter fw = new FileWriter(file);
        fw.write(txa_log.getText());
        fw.close();
    } catch (IOException e) {
        e.printStackTrace();
        Setting.addLog(e.getMessage());
    }
}
    public void LangProces() {
lb_lang.setText(LangM.lang);
lb_theme.setText(LangM.theme);
btn_choseColor.setText(LangM.colorChoser);
bt_saveLog.setText(LangM.saveLog);
bt_seeLog.setText(LangM.seeLog);
bt_saveTheme.setText(LangM.save);
saveLog.setText(LangM.saveLog);
close.setText(LangM.close);


}
    /**
     * @param args the command line arguments
     */
/*     public static void main(String args[]) {
        Setting.startingSetting();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SettingP().setVisible(true);
            }
        });
    } */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.buttons.ButtonN bt_saveLog;
    private view.buttons.ButtonN bt_saveTheme;
    private view.buttons.ButtonN bt_seeLog;
    private javax.swing.JButton btn_choseColor;
    private view.buttons.ButtonN buttonN1;
    private javax.swing.JMenuItem close;
    private javax.swing.JComboBox<String> cmb_lang;
    private javax.swing.JComboBox<String> cmb_theme;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lb_lang;
    private javax.swing.JLabel lb_theme;
    private javax.swing.JPanel pnl_setting;
    private javax.swing.JMenuItem saveLog;
    private view.TextField.TextFeild textFeild1;
    private javax.swing.JTextArea txa_log;
    // End of variables declaration//GEN-END:variables
}
