/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.panels;

import constants.Constantas;
import java.awt.Graphics;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

/**
 *
 * @author bismih
 */
public class MenuItems extends javax.swing.JPanel {

    private String a_text = "text";
    private String a_image = "search";

    /**
     * Creates new form MenuItems
     */
    public MenuItems() {
        super();
        initComponents();
        setBackground(Constantas.panelNormalColor());
        addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent fe) {
                System.out.println("odaklandı");
                setBackground(Constantas.panelFocusGain());
                lb_text.setForeground(Constantas.txDarkColor());
            }

            @Override
            public void focusLost(FocusEvent fe) {
                System.out.println("odak kayboldu");
                setBackground(constants.Constantas.panelNormalColor());
                lb_text.setForeground(Constantas.txNormalColor());

            }
        });
        addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                super.mousePressed(e);
                requestFocus();
            }

        });

    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        lb_text.setText(a_text);
        svgImage1.setImage(a_image);
        svgImage1.scale();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        svgImage1 = new view.image.SvgImage();
        lb_text = new javax.swing.JLabel();

        svgImage1.setText("svgImage1");
        svgImage1.setMinimumSize(new java.awt.Dimension(0, 0));

        lb_text.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(svgImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lb_text)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(svgImage1, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                .addGap(7, 7, 7))
            .addComponent(lb_text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lb_text;
    private view.image.SvgImage svgImage1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the text
     */
    public String getA_text() {
        return a_text;
    }

    /**
     * @param a_text the text to set
     */
    public void setA_text(String a_text) {
        this.a_text = a_text;
    }

    /**
     * @return the image
     */
    public String getA_image() {
        return a_image;
    }

    /**
     * @param a_image the image to set
     */
    public void setA_image(String a_image) {
        this.a_image = a_image;
    }
}
